### PR TITLE
add `engines` to package.json

### LINKED ISSUE #50: Node version
Specify node version in the README as well as in the package.json engines as [discussed here](https://github.com/stargate/stargate-mongoose/discussions/48)

### PR DESCRIPTION
**Pull request by vkarpov15**
**What this PR does**:

Fix #50. Warn user if they install stargate-mongoose with Node < 14

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Checklist**
- [ ] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [ ] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Review by jeffreyscarpenter — APPROVED** [review]

**Comment by kathirsvn** [comment]
@vkarpov15
I tested this by running npm install on the netlify ecommerce sample app project with node version 13 and I see below warning message along with a bunch of other warnings.
```log
npm WARN notsup Unsupported engine for stargate-mongoose@0.2.0-ALPHA-2: wanted: {"node":">=14.0.0"} (current: {"node":"13.14.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: stargate-mongoose@0.2.0-ALPHA-2
```

A couple of questions?

1. Should we generate package-lock.json file by running `npm install` and check in that as well?
2. I tested this with another sample NodeJS project (with node version < 14). I don't see the warning message. Here's the log. Am I missing something? 
```log
kathiresan.selvaraj@kselvaraj-rmbp16 CartsApi % node -v   
v13.14.0
kathiresan.selvaraj@kselvaraj-rmbp16 CartsApi % npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!

> stargate-mongoose@file:stargate-mongoose-0.2.0-ALPHA-2.tgz preinstall /Users/kathiresan.selvaraj/Documents/workspace/CartsApi/node_modules/stargate-mongoose
> node -p "'export const LIB_NAME = ' + JSON.stringify(require('./package.json').name) + ';'" > src/version.ts && node -p "'export const LIB_VERSION = ' + JSON.stringify(require('./package.json').version) + ';'" >> src/version.ts

npm WARN cartsapi@1.0.0 No description
npm WARN cartsapi@1.0.0 No repository field.

updated 63 packages and audited 63 packages in 1.893s
4 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities
kathiresan.selvaraj@kselvaraj-rmbp16 CartsApi % 
```

**Comment by vkarpov15** [comment]
1. I would advise _against_ committing and using a `package-lock.json` for the stargate-mongoose repo. The issue is that npm ignores individual packages' `package-lock.json` files, the installing project's `package-lock.json` takes precedence. So at best `package-lock.json` is useless in this repo, and at worst it may hide errors that developers doing a fresh install will see.
2. Can you please show me the repo you're working with? It also looks like you have a `package-lock.json` in that repo, my best guess is that the `package-lock.json` is causing you to `npm install` a cached version of stargate-mongoose. To confirm, try adding a `console.log()` in global scope somewhere in stargate-mongoose, and see if that log shows up when you run your project. To fix, you can just remove your `package-lock.json`.

FWIW, the netlify-functions-ecommerce example [explicitly disables package-lock.json currently](https://github.com/stargate/stargate-mongoose-sample-apps/blob/d76150bf75f2bd9df5fa32f13e2ebb827f93167e/netlify-functions-ecommerce/.npmrc). That is primarily to avoid any sort of caching issues when working with local tarballs of stargate-mongoose.

**Comment by kathirsvn** [comment]
@vkarpov15 Thanks for the details on the package-lock.json. I have added it to `.gitignore` now and also added `.npmrc` file with `package-lock` set to `false`. Please review and let me know if this looks good.

Also, in the sample app I have created, package-lock.json was the problem for not showing up the warning.

**Review by vkarpov15 — COMMENTED** [review]
LGTM :+1:

**Pull request merged**
