### PR TITLE
remove version.ts file in favor of importing from package.json

### PR DESCRIPTION
**Pull request by vkarpov15**
**What this PR does**:

Alternative approach for #126: I'm not entirely convinced we even need the `version.ts` file. Having the current version and package name in two places makes it possible that they will fall out of sync, and TypeScript does support importing json files with an additional compiler flag. So perhaps we just import `package.json`?

Only potential downside is that stargate-mongoose will now ship with a duplicate copy of `package.json` in `dist/package.json`, but that doesn't seem like a big problem. But I figure I'll put this out there as an option.

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Checklist**
- [ ] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [ ] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Comment by kathirsvn** [comment]
@vkarpov15 I'm good. The only reason for the current implementation was that we didn't want to include `package.json`. This approach looks good to me if having `package.json` is not a big problem.

**Comment by kathirsvn** [comment]
It looks like, there are some conflicts with other PRs that got merged recently.

**Comment by vkarpov15** [comment]
@kathirsvn I don't imagine having `package.json` in `dist` would be a big deal. It is an auto generated file, so no risk of it falling out of sync. I fixed the merge conflicts :+1:

**Comment by kathirsvn** [comment]
Cool, thanks 👍

**Review by kathirsvn — APPROVED** [review]
LGTM

**Pull request merged**
