### PR TITLE
support sort with `find()`

### PR DESCRIPTION
**Pull request by vkarpov15**
**What this PR does**:

Passes `sort` option to jsonapi similar to https://github.com/stargate/jsonapi/pull/384/files#diff-488243e12489a6552d96aa01dbbb63bd7ef9528ea445e7c86006ef1328b6c739 .

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Checklist**
- [ ] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [ ] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Comment by vkarpov15** [comment]
Tests failing because of https://github.com/stargate/jsonapi/issues/390 .

**Comment by vkarpov15** [comment]
Also added `findOneAndDelete()`, and verified that works with sort too. Added `count()` as well just in case.

**Comment by kathirsvn** [comment]
@vkarpov15 Looks like we need another release of JSON API before we can merge this?

**Comment by vkarpov15** [comment]
@kathirsvn not necessarily, the tests are only failing because I committed a test case for https://github.com/stargate/jsonapi/pull/392 . I skipped that test, so this PR should be good to merge.

**Comment by kathirsvn** [comment]
@vkarpov15 Got it! There is going to be another release of JSON API today. I'll put that test case back once published.

Also, I believe its because of IDE settings (or just got carried from old repo), there might be formatting issues in other files as well. I'm submitting a PR fixing the formatting issue in all files, as well as adding more test cases, ll submit that later today.

**Review by kathirsvn — APPROVED** [review]
LGTM

**Pull request merged**
