### PR TITLE
use mongoose 7

### LINKED ISSUE #23: Make driver mongoose 7 compatible
mongoose 7 is expected to be released soon.

Once we update stargate-mongoose to depend on mongoose 7, a couple of changes will be required.

* export Connection instead of getConnection()
* callbacks are removed from all the APIs, so have to make the functions async instead of relying on callbacks

Changes for this in a simple driver can be found here for reference
https://github.com/mongoosejs/in-memory-driver/pull/6

### PR DESCRIPTION
**Pull request by vkarpov15**
**What this PR does**:

Updates stargate-mongoose for Mongoose 7 support. 1) `getConnection` -> `Connection`, 2) no more callbacks in driver layer, 3) removed `remove()` and `update()`. Tested manually against ecommerce sample app, no problems.

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Checklist**
- [X] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [ ] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Comment by kathirsvn** [comment]
@vkarpov15 Should we remove the callbacks from src/collections/collection.ts as well?

**Comment by vkarpov15** [comment]
@kathirsvn sure, I can take that as part of this PR. It isn't critical, because Mongoose won't call those functions directly, but it will help make the code cleaner.

**Comment by vkarpov15** [comment]
@kathirsvn I removed remaining callbacks in 11a1f5c

**Review by kathirsvn — APPROVED** [review]
LGTM 👍

**Comment by vkarpov15** [comment]
I cleaned up the merge conflicts

**Comment by kathirsvn** [comment]
Hi @vkarpov15 I see this PR is closed now. Are you planning to reopen after the conflicts are resolved or to proceed with a new PR?

**Comment by vkarpov15** [comment]
@kathirsvn sorry, I accidentally closed this PR :facepalm: just re-opened it

**Comment by kathirsvn** [comment]
No problem. Merging it now.

**Pull request merged**
