### PR TITLE
Support sort with deleteOne, docs -> document/documents

### PR DESCRIPTION
**Pull request by vkarpov15**
**What this PR does**:

Various fixes for new jsonapi changes, taking into account https://github.com/stargate/jsonapi/pull/399, https://github.com/stargate/jsonapi/issues/141 + https://github.com/stargate/jsonapi/pull/402.

Also sundry other improvements:

1. `_.keys()` -> `Object.keys()`. No need to use `_.keys()`, `Object.keys()` is sufficiently well supported.
2. Make test titles more informative on jsonapi vs astra, currently printing `StargateMongoose - [object Object] Connection`
3. Assert that `TEST_DOC_DB` is set to a valid value.

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Checklist**
- [ ] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [ ] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Comment by kathirsvn** [comment]
@vkarpov15 Good improvements!
There are merge conflicts. Also, I believe this PR will work only with latest JSON API (i.e. the version yet to be published). If so, I can work on a JSON API release today.

**Comment by vkarpov15** [comment]
Correct, this will only work on latest JSON API. I'll fix the merge conflicts later today.

**Comment by kathirsvn** [comment]
@vkarpov15 I resolved the merge conflicts, updated the API version and also changed the JSON API port as required with the latest version (port has been changed from 8080 to 8181)

**Comment by vkarpov15** [comment]
LGTM, thanks @kathirsvn

**Comment by vkarpov15** [comment]
LGTM, thanks @kathirsvn

**Review by kathirsvn — APPROVED** [review]

**Pull request merged**
