### PR TITLE
call createDatabase() in createCollection()

### PR DESCRIPTION
**Pull request by vkarpov15**
**What this PR does**:

Re: discussion from #76. 

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Checklist**
- [ ] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [ ] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Comment by kathirsvn** [comment]
We should skip this for AstraDB since we will get a PERMISSION DENIED error back while trying to create a database.

**Comment by kathirsvn** [comment]
Should we get a global param, while creating connection to specify whether the end point is AstraDB or not?
This way, we can handle this use case as well as `createNamespaceOnConnect` flag internally in the driver? which will simplify the changes as we discussed [here](https://github.com/stargate/stargate-mongoose-sample-apps/pull/17#pullrequestreview-1392892729).

**Comment by vkarpov15** [comment]
Re: https://github.com/stargate/stargate-mongoose-sample-apps/pull/17#discussion_r1173815584 , "Maybe another option would be to assume that if authUrl option is set, we consider it a Stargate connection. If authUrl is not set, we consider it an Astra connection. What do you think?"

**Comment by kathirsvn** [comment]
Adding an `isAstra` flag as discussed [here](https://github.com/stargate/stargate-mongoose-sample-apps/pull/17#discussion_r1173836242).

**Comment by kathirsvn** [comment]
@vkarpov15 I added the `isAstra` option as well as related test cases in [this commit](https://github.com/stargate/stargate-mongoose/pull/72/commits/58e6e57fbb04b08d267f0e1a7932322a325591f8) in [this PR](https://github.com/stargate/stargate-mongoose/pull/72). Please review the same, we could close this PR since the other one covers this change as well.

**Comment by kathirsvn** [comment]
This can be closed since [this commit](https://github.com/stargate/stargate-mongoose/pull/72/commits/58e6e57fbb04b08d267f0e1a7932322a325591f8) covers this already.

**Pull request closed without merging**
