### PR TITLE
run full vector search integration tests against JSON API

### PR DESCRIPTION
**Pull request by vkarpov15**
**What this PR does**:

Got latest JSON API working and got 2 of the vector search tests running:

image

There's a couple of rough edges in the API that I'd like to smooth out and I'll patch up the rest of the vector search tests, but looks like vector search works :+1:

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Checklist**
- [ ] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [ ] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Comment by vkarpov15** [comment]
Made some more fixes, looks like tests all work. A couple of notes:

1. Currently cannot use `findOneAndReplace()` with `$vector` in `replacement`. Mongoose throws error `The replacement document must not contain atomic operators.` because it assumes that any fields that start with `$` are update operators. I'll look into this.
2. It is best practice to set `$vector` to undefined by default: `$vector: { type: [Number], default: () => void 0 }`. Otherwise, Mongoose will make `$vector` an empty array by default, which leads to JSON API throwing `SHRED_BAD_VECTOR_SIZE`.

**Comment by kathirsvn** [comment]
- LGTM overall.
- I think this can be merged only after the JSON API with vector search is published.
- Also, I created a ticket for usage of `$vector` in `replacement` https://github.com/stargate/stargate-mongoose/issues/121

**Review by kathirsvn — APPROVED** [review]

**Comment by jeffreyscarpenter** [comment]
Can we merge this now? @kathirsvn

**Comment by kathirsvn** [comment]
Let me update the JSON API version and see if the CI tests pass now before merging.

**Comment by kathirsvn** [comment]
I updated the JSON API and Stargate versions to the latest and the create collection API with vector options fail with below error. I just created a ticket for the same: https://github.com/stargate/jsonapi/issues/504 

```json
{
  "errors": [
    {
      "message": "INVALID_ARGUMENT: line 1:590 mismatched input '<' expecting ')' (...   set<text>,         query_vector_value  VECTOR[<]...)",
      "exceptionClass": "StatusRuntimeException"
    }
  ]
}
```

**Comment by kathirsvn** [comment]
Fixed the image to `coordinator-dse-next`, it looks good now.

**Pull request merged**
