### PR TITLE
correct return values for collection methods, remove duplicate tests

### PR DESCRIPTION
**Pull request by vkarpov15**
**What this PR does**:

I accidentally added some duplicate tests when merging #80, so removing those. Also added return types for all collection methods to work around some weird typing behaviors. All collection methods where returning `Promise<{}>`, which lead to some weird TS errors.

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Checklist**
- [ ] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [ ] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Comment by kathirsvn** [comment]
@vkarpov15 Could you please elaborate a little bit more on the TS errors? I was just trying to reproduce the error in the `main` branch and I don't see any errors, all tests look good (`npm run build` looks good as well). So I'm curios what this error could be.

**Comment by kathirsvn** [comment]
Ah I see a bunch of errors in the tests where the fields of these responses from the collection operations are accessed. Is that what are we talking about?

**Comment by vkarpov15** [comment]
I'm not exactly sure why these errors aren't showing up in `npm run build`. For me, they show up in VSCode:

Screenshot_2023-04-26_17-31-25

**Comment by vkarpov15** [comment]
So the TS errors aren't showing up in `npm run build` because `npm run build` doesn't compile the tests. Run `./node_modules/.bin/tsc` and you'll see a bunch of errors like the following

```
tests/collections/db.test.ts:85:31 - error TS2339: Property 'status' does not exist on type '{}'.

85       assert.strictEqual(res2.status.ok, 1);
                                 ~~~~~~

```

Not sure why ts-mocha isn't complaining about compiler errors in the test files.

**Comment by kathirsvn** [comment]
Got it. It just shows up for me as well, in the IDE. This change looks good to me, merging now. But it looks like still there are some errors, let me look into them as well, after merging this.

**Review by kathirsvn — APPROVED** [review]

**Pull request merged**
