### PR TITLE
Serialize and deserialize $objectId

### PR DESCRIPTION
**Pull request by vkarpov15**
**What this PR does**:

Re: stargate/data-api#936 and other PRs. Serialize objectids into `{ $objectId: str }` and handle deserializing objectids from `{ $objectId: str }`.

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Checklist**
- [ ] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [ ] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Comment by vkarpov15** [comment]
I did some testing and this causes errors with data-api@1.0.2: `[{"message":"Bad type for '_id' property: Document Id must be a JSON String, Number, Boolean, EJSON-Encoded Date Object or NULL instead got OBJECT","errorCode":"SHRED_BAD_DOCID_TYPE"}]`

We can still deserialize `$objectId` just fine, it's just serializing `$objectId`. So I undid the `serializeValue()` changes for now until we're reasonably certain that no one will ever use data-api@1.0.2 or lower. Including Astra.

Also, I don't see anywhere where we list version compatibility for data-api. Maybe add that to https://github.com/stargate/stargate-mongoose?tab=readme-ov-file#version-compatibility ?

**Comment by tatu-at-datastax** [comment]
Correct: this feature only works with 1.0.3 and above.

**Review by kathirsvn — CHANGES_REQUESTED** [review]
Hi @vkarpov15 , the changes LGTM. There are some lint warnings, can we fix these please?

**Comment by kathirsvn** [comment]
> Also, I don't see anywhere where we list version compatibility for data-api. Maybe add that to https://github.com/stargate/stargate-mongoose?tab=readme-ov-file#version-compatibility ?

@vkarpov15 Yes, we can start adding Data API here in the README. So far, we didn't require that I think.

**Comment by vkarpov15** [comment]
@kathirsvn fixed, please take a look

**Review by kathirsvn — APPROVED** [review]

**Pull request merged**
